server:
    port: 10060


spring:
    datasource:
        write:
            url: jdbc:sqlserver://127.0.0.1:1433;database=TEST1;integratedSecurity=false;autoReconnect=true;
            username: sa
            password: ABCabc123
        read:
            -   url: jdbc:sqlserver://127.0.0.1:1433;database=TEST2;integratedSecurity=false;autoReconnect=true;
                username: sa
                password: ABCabc123

logging:
    level:
        root : debug
